name: Python application

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 freeze > requirements.txt
        pip3 install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip3 install pylint
        pip3 install pylint --upgrade
        find . -type f -name "*.py" | xargs pylint
    - name: Test with pytest
      run: |
        pip3 install pytest
        pip3 install pytest-cov
        pytest --cov-report html:cov_html
